// db/setup.js
// Creates the schema and seeds demo accounts for whichever database is active.
// Run with:  npm run setup
require('dotenv').config();
const bcrypt = require('bcryptjs');
const db = require('../src/db');

// ---- Schema (dialect-aware) -------------------------------------------------
// Oracle: wrap each CREATE in a PL/SQL block that ignores ORA-00955
// ("name is already used by an existing object") so re-running is safe.
const oracleTable = (sql) =>
  `BEGIN EXECUTE IMMEDIATE '${sql.replace(/\s+/g, ' ').trim()}'; ` +
  `EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;`;

const oracleSchema = [
  oracleTable(`CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(150) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP)`),
  oracleTable(`CREATE TABLE courses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    description VARCHAR2(2000),
    category VARCHAR2(100),
    educator_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP)`),
  oracleTable(`CREATE TABLE enrollments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    learner_id NUMBER NOT NULL,
    enrolled_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_enroll UNIQUE (course_id, learner_id))`),
];

const isMssql = db.client === 'mssql';

const sqlServerSchema = [
      `IF OBJECT_ID('enrollments','U') IS NULL
       CREATE TABLE enrollments (
         id INT IDENTITY(1,1) PRIMARY KEY,
         course_id INT NOT NULL,
         learner_id INT NOT NULL,
         enrolled_at DATETIME2 DEFAULT SYSUTCDATETIME(),
         CONSTRAINT uq_enroll UNIQUE (course_id, learner_id)
       );`,
      `IF OBJECT_ID('courses','U') IS NULL
       CREATE TABLE courses (
         id INT IDENTITY(1,1) PRIMARY KEY,
         title NVARCHAR(200) NOT NULL,
         description NVARCHAR(2000) NULL,
         category NVARCHAR(100) NULL,
         educator_id INT NOT NULL,
         created_at DATETIME2 DEFAULT SYSUTCDATETIME(),
         updated_at DATETIME2 DEFAULT SYSUTCDATETIME()
       );`,
      `IF OBJECT_ID('users','U') IS NULL
       CREATE TABLE users (
         id INT IDENTITY(1,1) PRIMARY KEY,
         name NVARCHAR(150) NOT NULL,
         email NVARCHAR(255) NOT NULL UNIQUE,
         password_hash NVARCHAR(255) NOT NULL,
         role NVARCHAR(20) NOT NULL,
         created_at DATETIME2 DEFAULT SYSUTCDATETIME()
       );`,
];

const sqliteSchema = [
      `CREATE TABLE IF NOT EXISTS users (
         id INTEGER PRIMARY KEY AUTOINCREMENT,
         name TEXT NOT NULL,
         email TEXT NOT NULL UNIQUE,
         password_hash TEXT NOT NULL,
         role TEXT NOT NULL CHECK (role IN ('educator','learner')),
         created_at TEXT DEFAULT (datetime('now'))
       );`,
      `CREATE TABLE IF NOT EXISTS courses (
         id INTEGER PRIMARY KEY AUTOINCREMENT,
         title TEXT NOT NULL,
         description TEXT,
         category TEXT,
         educator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
         created_at TEXT DEFAULT (datetime('now')),
         updated_at TEXT DEFAULT (datetime('now'))
       );`,
      `CREATE TABLE IF NOT EXISTS enrollments (
         id INTEGER PRIMARY KEY AUTOINCREMENT,
         course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
         learner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
         enrolled_at TEXT DEFAULT (datetime('now')),
         UNIQUE (course_id, learner_id)
       );`,
];

const schema = db.client === 'oracle' ? oracleSchema : isMssql ? sqlServerSchema : sqliteSchema;

async function tableHasRows(table) {
  const row = await db.get(`SELECT COUNT(*) AS c FROM ${table}`);
  return (row.c || row.C || 0) > 0;
}

async function main() {
  await db.init();
  console.log(`Setting up schema for driver: ${db.client}`);

  for (const stmt of schema) {
    await db.exec(stmt);
  }
  console.log('Tables ready.');

  if (await tableHasRows('users')) {
    console.log('Users already exist — skipping seed.');
    await db.close();
    return;
  }

  // ---- Seed demo accounts -------------------------------------------------
  const pw = (p) => bcrypt.hashSync(p, 10);

  const educator = await db.run(
    'INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)',
    ['Dr. Aisha Educator', 'educator@eduseria.com', pw('Educator123!'), 'educator']
  );
  const learner = await db.run(
    'INSERT INTO users (name, email, password_hash, role) VALUES (?, ?, ?, ?)',
    ['Sam Learner', 'learner@eduseria.com', pw('Learner123!'), 'learner']
  );

  const c1 = await db.run(
    'INSERT INTO courses (title, description, category, educator_id) VALUES (?, ?, ?, ?)',
    ['Introduction to Cloud Computing', 'Core concepts of IaaS, PaaS and SaaS with hands-on labs.', 'Technology', educator.lastID]
  );
  await db.run(
    'INSERT INTO courses (title, description, category, educator_id) VALUES (?, ?, ?, ?)',
    ['Academic Writing 101', 'Build strong writing habits for university-level work.', 'Languages', educator.lastID]
  );

  await db.run(
    'INSERT INTO enrollments (course_id, learner_id) VALUES (?, ?)',
    [c1.lastID, learner.lastID]
  );

  console.log('Seed complete.');
  console.log('  Educator login: educator@eduseria.com / Educator123!');
  console.log('  Learner  login: learner@eduseria.com  / Learner123!');
  await db.close();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
